apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
    domain: orchestration
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
    domain: tracking
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
    domain: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
    domain: serving
