fullnameOverride: postgres-mlflow

auth:
  username: mlflow
  database: mlflow
  existingSecret: postgres-mlflow-creds
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: microk8s-hostpath
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
  pgHbaConfiguration: |-
    local all all trust
    host  all all 0.0.0.0/0 md5
    host  all all ::/0      md5

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: mlflow
    labels:
      release: kube-prom-stack
