fullnameOverride: postgres-airflow

auth:
  username: airflow
  database: airflow
  existingSecret: postgres-airflow-creds
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: microk8s-hostpath
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
  pgHbaConfiguration: |-
    local all all trust
    host  all all 0.0.0.0/0 md5
    host  all all ::/0      md5

metrics:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 500m
  serviceMonitor:
    enabled: true
    namespace: airflow
    labels:
      release: kube-prom-stack
