apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-pvcs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ftuga/Vigilancia-Obst-trica-Municipal.git
    targetRevision: main
    path: k8s/infra/airflow-pvcs
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
