apiVersion: v1
kind: Service
metadata:
  name: api-predict-mme
  namespace: apps
  labels:
    app.kubernetes.io/name: api-predict-mme
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: api-predict-mme
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30601
