apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: apps
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "postgres-airflow",
          "Group": "MME",
          "Host": "postgres-airflow.airflow.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "airflow",
          "Username": "airflow",
          "SSLMode": "prefer"
        },
        "2": {
          "Name": "postgres-mlflow",
          "Group": "MME",
          "Host": "postgres-mlflow.mlflow.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "mlflow",
          "Username": "mlflow",
          "SSLMode": "prefer"
        }
      }
    }
