apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: apps
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/part-of: vigilancia-obstetrica-municipal
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: locust
  ports:
    - name: web
      port: 8089
      targetPort: 8089
      nodePort: 30089
